<section class="home" id="acceuil">
    <div class="max-width">
        <div class="home-content">
            <div class="text1">For the love of delicious food </div>
        </div>
    </div>

</section>
<section class="service_item1" id="no_menu">
    <h1>NOTRE MENU</h1>
</section>
<section class="p_120" id="service">
        <?php foreach($categories as $categorie): ?>
        <div class="separation">
            <h4 class="service_item shadow-lg "><?= $categorie['nom'] ;?> menu</h4>
             <a href="./menu/index.php?idcategorie=<?=$categorie['id']?>">
                <img  src="./categorie_photo/<?= explode("/",$categorie['photo'])[2] ?>" alt="" class="photo_menu1">
            </a>
        </div>
        <?php endforeach; ?>
</section>

<!--========== about us ==========-->
<section class="  " id="obout_us">
    <span class="section-subtitle">Offering</span>
    <h2 class="section-title">Our amazing services</h2>

    <div class="services__container  bd-grid">
        <div class="services__content">
            <img src="./assets/photo/excellence.png" alt="" class="services__img">
            <h3 class="services__title">Excellent food</h3>
            <p class="services__description">We offer our clients excellent quality services for many years, with
                the best and delicious food in the city.</p>
        </div>

        <div class="services__content">
            <img src="./assets/photo/fast_food.png" alt="" class="services__img">
            <h3 class="services__title">Fast food</h3>
            <p class="services__description">We offer our clients excellent quality services for many years, with
                the best and delicious food in the city.</p>
        </div>

        <div class="services__content">
            <img src="./assets/photo/Delivery.png" alt="" class="services__img">
            <h3 class="services__title">Delivery</h3>
            <p class="services__description">We offer our clients excellent quality services for many years, with
                the best and delicious food in the city.</p>
        </div>
    </div>
</section>

<!-- contact section start -->
<div class="section6" id="contact">
    <p> Get our daily food items delivered to your email</p>
    <div class="form-group">
        <form id="subscribtionList">
            <div class="rows">
                <div class="col-md-8">
                    <input type="email" id="emailaddress" class="form-control" placeholder="Your email">
                </div>
                <div class="col-md-4">
                    <input type="button" value="Subscribe" id="subscribe" class="form-control">
                </div>
            </div>
        </form>
    </div>
</div>
<!-- Section 7 includes the website footer-->
<div class="section7">
    <div class="footer">
        <h5>
            <img src="../assets/photo/logo_white.png" alt="White Logo">MENU
        </h5>
        <p>Thats what we are</p>
        <i class="fa fa-facebook-square fa-lg" aria-hidden="true"></i>
        <i class="fa fa-twitter-square fa-lg" aria-hidden="true"></i>
        <i class="fa fa-pinterest-square fa-lg" aria-hidden="true"></i>
        <p id="copyright">2023 Menu Restaurant</p>
    </div>
</div>






</body>

</html>