
    <section class="home" id="acceuil">
        <div class="max-width">
            <div class="home-content">
                <div class="text1">For the love of delicious food </div>
            </div>
        </div>

    </section>
    <section class="service_item1" id="no_menu">
        <h1>NOTRE MENU</h1>
    </section>
    <section class="p_120" id="service">
        <article>
            <div class="separation">
                <h4 class="service_item shadow-lg ">pizza menu</h4>
                <a href="./menu/pizzamenu.php">
                    <img src="assets/photo/pizza.jpg" alt="" class="photo_menu1">
                </a>
            </div>

            </div>
            <div class="separation">
                <h4 class="service_item shadow-lg ">drink menu</h4>
                <a href="">
                    <img src="assets/photo/drink.jpg" alt="" class="photo_menu1">
                </a>
            </div>
            </div>


        </article>
        <article>
            <div class="separation">
                <h4 class="service_item shadow-lg ">sweet menu</h4>
                <a href="">
                    <img src="assets/photo/sweet.jpg" alt="" class="photo_menu1">
                </a>
            </div>

            </div>
            <div class="separation">
                <h4 class="service_item shadow-lg ">breakfast menu</h4>
                <a href="">
                    <img src="assets/photo/breakfast.jpg
                    " alt="" class="photo_menu1">
                </a>
            </div>

            </div>
        </article>
        <article>
            <div class="separation">
                <h4 class="service_item shadow-lg ">menu of dishes</h4>
                <a href="">
                    <img src="assets/photo/menu1.jpg" alt="" class="photo_menu1">
                </a>
            </div>

            </div>
            <div class="separation">
                <h4 class="service_item shadow-lg ">burger menu</h4>
                <a href="">
                    <img src="assets/photo/burger2.jpg" alt="" class="photo_menu1">
                </a>
            </div>

            </div>
        </article>
    </section>

    <!--========== about us ==========-->
    <section class="  " id="obout_us">
        <span class="section-subtitle">Offering</span>
        <h2 class="section-title">Our amazing services</h2>

        <div class="services__container  bd-grid">
            <div class="services__content">
                <img src="./assets/photo/excellence.png" alt="" class="services__img">
                <h3 class="services__title">Excellent food</h3>
                <p class="services__description">We offer our clients excellent quality services for many years, with
                    the best and delicious food in the city.</p>
            </div>

            <div class="services__content">
                <img src="./assets/photo/fast_food.png" alt="" class="services__img">
                <h3 class="services__title">Fast food</h3>
                <p class="services__description">We offer our clients excellent quality services for many years, with
                    the best and delicious food in the city.</p>
            </div>

            <div class="services__content">
                <img src="./assets/photo/Delivery.png" alt="" class="services__img">
                <h3 class="services__title">Delivery</h3>
                <p class="services__description">We offer our clients excellent quality services for many years, with
                    the best and delicious food in the city.</p>
            </div>
        </div>
    </section>






</body>

</html>