<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="./assets/css/style.css">
    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
    <script src="https://kit.fontawesome.com/c5bebe1cfa.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>
    <?= $page_titel ?>
</title>
<style>
     .sidebar_admin {
  min-width: 17rem;
  width: 17rem;
  position: fixed;
  height: 100vh;
  box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.1);
  transition: all 0.4s;
}

.page-content_admin {
  width: calc(100%-17rem);
  margin-left: 17rem;
  transition: all 0.4s;
}

#sidebar_admin.active {
  margin-left: -17rem;
}

#content_admin.active {
  width: 100%;
  margin: 0;
}

@media (max-width:768px) {
  #sidebar_admin {
      margin-left: -17rem;
      position: fixed;
  }

  #sidebar_admin.active {
      margin-left: 0;
  }

  #content_admin {
      width: 100%;
      margin: 0;
  }

  #content_admin.active {
      margin-left: 17rem;
      width: calc(100%-17rem);
  }
}
</style>
</head>
<body>
    <!-- <img src="./assets/photo/logo.png" alt="" class="logo sticky-top"> -->
    <?php if(isset($_SESSION['id'])): ?>
        <div class="sidebar_admin fixed-top" id="sidebar_admin">
        <div class="py-4 mx-3">
           <div class="mosule d-flex alig-items-center">
                <img src="" width="100" height="80" class="rounded-circle img-thumbnail shadow-sm" alt="">
              <div class="body py-3 px-2">
                 <p class="m-0"><?=$_SESSION['id'];?></p>
                 <p class="font-weight-normal text-muted">Front End</p>
              </div>
          </div>
       </div>

    <span class="fs-5 fw-semibold px-5 ">Dashboard</span>
    </a>

    <ul class="list-unstyled flex-column ps-0 mx-4 mt-4">

      <li class="mb-3">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="true">
          Home
        </button>
        <div class="collapse show" id="home-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="../profiladmin" class="link-dark rounded">Overview <i class="fa-solid fa-chart-line px-2"></i></a></li>
        </div>
      </li>


      <li class="mb-3">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#dashboard-collapsee" aria-expanded="false">
          User Manager
        </button>
        <div class="collapse" id="dashboard-collapsee">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="../consulte_user/" class="link-dark rounded">Consulte User <i class="fa-solid fa-clipboard-list px-2"></i></a></li>
            <li><a href="../consulte_user_blocked/" class="link-dark rounded">Consulte user deleted<i class="fa-solid fa-ban px-1"></i> </a></li>
          </ul>
        </div>
      </li>
   
      <div class="py-5 mt-5 px-5">
          <a class="text-decoration-none text-dark font-weight-bold" href="../logout.php">Log Out <i class="fa-solid fa-right-from-bracket px-2"></i></a>
      </div>
    </div>

</div>
<div class="page-content_admin" id="content_admin">
         <div class="bg-info p-3"> 
         <button class="btn btn-ou  tline-dark mx-1"  id="btn1"><i class="fa-solid fa-list"></i></button>
           <div class="float-end">
            <a class="mx-3" style="cursor:pointer;position:relative" > 
            <button class="btn btn-outline-primary position-relative " onclick="toasty()">
              <i class="text-dark fa-solid fa-bell"></i>
               <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                        5 
              </span>
          </button>
            </a>
            </div>
        </div> 
        <?php include $template.".phtml"; ?>
    </div>
     <?php else : ?>      

    <?php if ($template == ""): ?>
        <nav class=" d-inline-block text-center shadow-lg mb-5 nav sticky-top">

            <a href="#acceuil" class="text-decoration-none  btn-light col">Acceuil</a>
            <a href="#no_menu" class="text-decoration-none  btn-light col">menu</a>
            <a href="#obout_us" class="text-decoration-none  btn-light col">about us</a>
            <a href="./produit" class="text-decoration-none  btn-light col">contact</a>
            <a href="./signUp/index.php" class="sign_up text-decoration-none  btn-light col">sign up</a>
        </nav>
    <?php else :?>
        <nav class=" d-inline-block text-center shadow-lg mb-5 nav sticky-top">
            <a href="../index.php" class="text-decoration-none  btn-light col">Acceuil</a>
            <a href="../index.php" class="text-decoration-none  btn-light col">menu</a>
            <a href="../index.php" class="text-decoration-none  btn-light col">about us</a>
            <a href="../produit" class="text-decoration-none  btn-light col">contact</a>
            <a href="../signUp/index.php" class="sign_up text-decoration-none  btn-light col">sign up</a>
        </nav>
    <?php endif; ?>
    <?php include ($template=="" ? "index" : $template) .".phtml"; ?><!--Dynamique-->

    <?php endif;?>
</body>

<script>
     try {

let btn = document.querySelector("#btn1");
let side_bar = document.querySelector("#sidebar_admin");
let content = document.querySelector("#content_admin");
btn.addEventListener("click", function () {
  side_bar.classList.toggle("active");
  content.classList.toggle("active");
});
}catch (e){}
</script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/c5bebe1cfa.js" crossorigin="anonymous"></script>
</html>