<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>

<div class="container">
        <div class="row mt-4">
         <div class="col">
          <!-- <a href="http:./index.php"><button> Add Commande </button> </a> -->
          
           </div>
           </div>
           

                <div class="food-menu-box">
                    <!-- <div class="food-menu-img">
                        <img src="" alt="Chicke Hawain Pizza" class="img-responsive img-curve">
                    </div> -->

                    <div class="food-menu-desc">
                        <h4>
                            <?php echo $_POST['nom'] ?> <?php echo $_POST['prenom'] ?>
                        </h4>
                        <h4>
                            <?php echo $_POST['codepostale'] ?>
                        </h4>
                        <h4>
                            <?php echo $_POST['ville'] ?>
                        </h4>
                        <h4>
                            <?php echo $_POST['tlf_num'] ?>
                        </h4>
                        
                      
                        <br>
                        <form action="index.php" method="POST">
                            <input type="hidden" value="<?= $_POST['nom']?>" name="nom">
                            <input type="hidden" value="<?= $_POST['prenom']?>" name="prenom">
                            <input type="hidden" value="<?= $_POST['adresse_email']?>" name="adresse_email">
                            <input type="hidden" value="<?= $_POST['ville']?>" name="ville">
                            <input type="hidden" value="<?= $_POST['codepostale']?>" name="codepostale">
                            <input type="hidden" value="<?= $_POST['tlf_num']?>" name="tlf_num">
                            

                       <button type="submit" name="confirmer" class="btn btn-primary" >confirmer</button> 
                       <button><a href="delete.php?id=<?= $commandes['id']; ?>" class="btn btn-danger" onclick=" return confirm('do you want Annuler <?php echo $commandes['nom'] ?>');">annuler</a></button> 
                       </form>
                    </div>
                </div>


            
        </div>
    
</body>
</html>