<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    

<div class="container">
        <div class="row mt-4">
         <div class="col">
          <!-- <a href="http:./index.php"><button> Add Commande </button> </a> -->
          
           </div>
           </div>
           

                <div class="food-menu-box">
                    <!-- <div class="food-menu-img">
                        <img src="" alt="Chicke Hawain Pizza" class="img-responsive img-curve">
                    </div> -->
                    <form action="./index.php" method="POST">
                    <div class="food-menu-desc">
                        <h4>
                            <?php echo $_SESSION['nom'] ?> <?php echo $_SESSION['prenom'] ?>
                        </h4>
                        
                        <h4>
                            <?php echo $_SESSION['ville'] ?>
                        </h4>
                        <h4>
                            <?php echo $_SESSION['tlf_num'] ?>
                        </h4>
                        
                      
                        <br>
                       

                       <button type="submit" name="confirmer" class="btn btn-primary" >confirmer</button> 
                       <button><a class="btn btn-danger" onclick=" return confirm('do you want Annuler <?php echo $_SESSION['nom'] ?>');">annuler</a></button> 
                       
                    </div>
                    </form>
                </div>


            
        </div>
    
</body>
</html>