<link rel="stylesheet" href="../assets/css/style.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

<div class="all container">
    <div class="card shadow-lg mt-3">
        <h3 style="text-align: center; color: red; filter: drop-shadow(0 0 10px var(--color-success));">Add Categories</h3>

        <form class="formu" action="index.php" method="POST" enctype="multipart/form-data" style="margin: 50px;">
        <?php if(array_key_exists("message",$_GET)): ?>
                        <div class="alert alert-<?=$_GET['type']?>">
                           <?php echo $_GET['message'] ?>
                        </div>
                      <?php endif; ?>
            <div class="mb-3">
               
                <label class="form-label">Categorie name</label>
                <input type="text" name="nom" placeholder="Name..." class="form-control  <?= array_key_exists('nom',$errors) ? 'is-invalid' :''?> "  value="<?= $nom ?>">
                <small class="text-danger"><?php echo array_key_exists("nom",$errors) ?   $errors['nom'] : '' ?></small>
               <br>
               
                <label class="form-label">Categorie picture</label><br>
                <input type="file" name="photo">
               
                <br>
                <br>



            </div>

            <button type="submit" name="submit" class="btn btn-primary">AJOUTER CATEGORIES</button>
            <button type="reset" class="btn btn-danger">FERMER</button>
        </form>

    </div>