<style>
    img{
        width: 100%;
        height: 100%;
    }
</style>
<link rel="stylesheet" href="../assets/css/style.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

<div class="d-flex p-3 m-4 justify-content-center">   
    <div class="col-xl-10 col-md-12 col-lg-12">
          <div class="row shadow-lg rounded">
                <div class="col-lg-6 d-none d-lg-block bg-secondary">
                    <img src="../assets/images/login.png" alt="">
                </div>
                <div class=" col-lg-6 py-5">
                      <div class="text-center">
                        <h1 class="h4 text-gray-900 mb-5">Welcome !</h1>
                      </div>
                    <form action="<?=$_SERVER['PHP_SELF']?>" method="POST">
                     <div class="mb-4">
                          <input  type="text" placeholder="Name..." name="nom" class="form-control rounded-pill p-4" id="exampleInputNom">
                      </div>
                      <div class="mb-4">
                          <input  type="text" placeholder="LastName..." name="prenom" class="form-control rounded-pill p-4" id="exampleInputPrenom">
                      </div>
                      <div class="mb-4">
                          <input  type="text" placeholder="Entrer Email Address..." name="email" class="form-control rounded-pill p-4" id="exampleInputEmail1">
                      </div>
                      <div class="mb-4">
                         <input type="password" placeholder="Password" name="password" class="form-control rounded-pill p-4" id="exampleInputPassword1">
                      </div>
                      <div class="mb-5">
                          <input  type="text" placeholder="Entrer Number Phone..." name="email" class="form-control rounded-pill p-4" id="exampleInputEmail1">
                      </div>
                      
                          <button style="font-size:19px" type="submit" name="submit" class="btn btn-primary btn-block w-100 rounded-pill">Sign in</button>
                      </form>
                      <hr>
                       <div class="fin text-center">
                              <a href="../login/index.php">login !</a>
                      </div> 
                </div>
          </div>
    </div>
</div>