<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up Form</title>
    <link rel="stylesheet" href="../assets/css/style.css">
</head>
<body>

<div class="container right-panel-active">
	<div class="container__form container--signup">
		<form action="#" class="form" id="form1">
			<h2 class="form__title">Sign Up</h2>
			<input type="text" placeholder="Nom" class="input" />
            <input type="text" placeholder="Prenom" class="input" />
			<input type="email" placeholder="Email" class="input" />
			<input type="password" placeholder="Password" class="input" />
            <input type="text" placeholder="num_tlf" class="input" />
            <input type="file" name="file" class="input">
			<button class="btn">Sign Up</button>
		</form>
	</div>


	<div class="container__overlay">
		<div class="overlay">
			<div class="overlay__panel overlay--left">
				
			</div>
		</div>
	</div>
</div>
    

</body>
</html>

<script>


</script>
