<link rel="stylesheet" href="../assets/css/style.css">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

<body style="background-color: #ececec ;">
    <h2 class="text-center">users list <a href="../addproduit"><button
                class="btn btn-primary">show user</button></a></h2>

    <section class="food-menu">
        <div class="container">
            <?php
            foreach ($users as $user):
                ?>

                <div class="food-menu-box">
                    <!-- <div class="food-menu-img">
                        <img src="" alt="Chicke Hawain Pizza" class="img-responsive img-curve">
                    </div> -->

                    <div class="food-menu-desc">
                        <h4>
                            <?php echo $user['nom'] ?>
                        </h4>
                        <p class="user-email">
                            <?php echo $user['email'] ?>
                        </p>
                        <p class="user-num">
                            <?php echo $user['num_tlf'] ?>
                        </p>
                        <br>

                        <a href="./update/?=<?= $user['id']; ?>" class="btn btn-primary"><i style='font-size:24px' class='fas'>&#xf044;</i></a>
                        <a href="./delete.php?id=<?= $user['id']; ?>">
                            <button class="btn btn-danger"
                                onclick=" return confirm('do you want Delete <?php echo $user['nom'] ?>');"><i class="fa-solid fa-trash"></i></button></a>

                    </div>
                </div>


            <?php endforeach; ?>
        </div>


    </section>


</body>