<div class="container mt-5 py-5">
    <h2 class="mb-5">ListUsers</h2>
    <table class="table ">
        <thead>
            <td>#</td>
            <td>Photo</td>
            <td>Nom</td>
            <td>Email</td>
            <td>Phone</td>
            <td>Operation</td>
        </thead>
      <?php if(count($users)==0): ?>
         <tbody>
      <tr>
         <td colspan="6" class="text-center">No UserFound</td>
      </tr>
        </tbody> 
        <?php else:?>
        <tbody>

            <?php foreach($users as $user): ?>
            <tr>
                <td><?= $user['id']; ?></td>
                <td>
                    <img width="100px" src="<?= $user['photo'] ?>" alt="">
                </td>
                <td><?= $user['nom']; ?></td>
                <td><?= $user['email']; ?></td>
                <td><?= $user['num_tlf'];?></td>
                <td>
                 
                        <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal<?=$user['id']?>">
                            <i class="bi bi-trash"></i>
                        </button>

<div class="modal fade" id="exampleModal<?=$user['id']?>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Confirm Deleted</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Do You Want to delete <?=$user['nom']?>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <a href="./delete.php?id=<?=$user['id'];?>">
        <button type="button" class="btn btn-danger">
             Delete
        </button>
        </a>
      </div>
    </div>
  </div>
</div>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
        <?php  endif;?>
    </table>
</div>