<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <title>Document</title>
</head>
<body>
<div class="all container">
    <div class="card shadow-lg mt-3">
        <!-- <h3 style="text-align: center; color: red; filter: drop-shadow(0 0 10px var(--color-success));">Add Categories</h3> -->

        <form class="formu" action="index.php" method="POST" enctype="multipart/form-data" style="margin: 50px;">
        <?php if(array_key_exists("message",$_GET)): ?>
                        <div class="alert alert-<?=$_GET['type']?>">
                           <?php echo $_GET['message'] ?>
                        </div>
                      <?php endif; ?>
            <div class="mb-3">
               
                <!-- <label class="form-label">Categorie name</label> -->
                <input type="text" name="nom" placeholder="Name..." class="form-control rounded-pill p-4 <?= array_key_exists('nom',$errors) ? 'is-invalid' :''?> "  value="<?= $nom ?>">
                <small class="text-danger"><?php echo array_key_exists("nom",$errors) ?   $errors['nom'] : '' ?></small>
               <br>
               <input  type="text" placeholder="LastName..." name="prenom" class="form-control rounded-pill p-4 <?= array_key_exists('prenom',$errors) ? 'is-invalid' :''?>"  value="<?= $prenom ?>" >
                <small class="text-danger"><?php echo array_key_exists("prenom",$errors) ?   $errors['prenom'] : '' ?></small>
                <br>
                <input  type="text" placeholder="Entrer Email Address..." name="Email" class="form-control rounded-pill p-4 <?= array_key_exists('Email',$errors) ? 'is-invalid' :''?>"  value="<?= $Email ?>" >
                <small class="text-danger"><?php echo array_key_exists("Email",$errors) ?   $errors['Email'] : '' ?></small>
                <br>
                <input type="text" placeholder="ville" name="ville" class="form-control rounded-pill p-4 <?= array_key_exists('ville',$errors) ? 'is-invalid' :''?>"  value="<?= $ville ?>" >
                <small class="text-danger"><?php echo array_key_exists("ville",$errors) ?   $errors['ville'] : '' ?></small>
                <br>
                
                <input  type="text" placeholder="Entrer Number Phone..." name="tlf_num" class="form-control rounded-pill p-4 <?= array_key_exists('tlf_num',$errors) ? 'is-invalid' :''?>"  value="<?= $tlf_num ?>" >
                <small class="text-danger"><?php echo array_key_exists("tlf_num",$errors) ?   $errors['tlf_num'] : '' ?></small>
                <br>
               
                
               
    



            </div>

            <button type="submit" name="submit" class="btn btn-primary">CONTINUE</button>
            <button type="reset" class="btn btn-danger">FERMER</button>
        </form>

    </div>

            
    
</body>
</html>