<div class="container">
    <h2 class="text-center mt-1">Products list</h2>
          <a href="../addproduit/" class="mx-2"><button class="btn btn-outline-primary"> Add Product </button> </a>
             <div class="row mt-2 py-2">
                 <?php foreach ($produits as $produit):
                ?>
                 <div class="col-lg-4">
                        <div class="card">
                             <div class="card-header text-center" style="font-weight:bold;font-size:18px">
                                <?= $produit['nom'] ?>
                             </div>
                             <div class="card-body text-center">
                                <img width="200px" height="200px"  src="<?= $produit['PhotoProduit']?>" alt="Chicke Hawain Pizza" class="img-responsive img-curve rounded shadow">
                                    Prix :<span><?=$produit['prix']?></span>
                                    <br>
                                    Description : <span><?=$produit['description']?></span>
                                    <br>
                                    Category : <?= GetNomCategory($produit['idCategory'],$db); ?>
                                    <div class="d-flex justify-content-center mb-2 mt-2">
                                        <a href="./update/?=<?= $produit['id']; ?>" class="btn btn-primary mx-2">modifier</a>
                                        <a href="delete.php?id=<?= $produit['id']; ?>" class="btn btn-danger" onclick=" return confirm('do you want Delete <?php echo $produit['nom'] ?>');">suprimer</a>
                                      </div>
                            </div>
                        </div>
                        </div>
            <?php endforeach; ?>
             </div>
        </div>
        </div>