<link rel="stylesheet" href="../assets/css/style.css">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

<body style="background-color: #ececec ;">
    <h2 class="text-center">product list <a href="../addproduit"><button
                class="btn btn-primary">add_produit</button></a></h2>

    <section class="food-menu">
        <div class="container">
            <?php
            foreach ($produits as $produit):
                ?>

                <div class="food-menu-box">
                    <div class="food-menu-img">
                        <img src="<?= $produit['PhotoProduct'] ?>" alt="Chicke Hawain Pizza" class="img-responsive img-curve">
                    </div>

                    <div class="food-menu-desc">
                        <h4>
                            <?php echo $produit['nom'] ?>
                        </h4>
                        <p class="food-price">
                            <?php echo $produit['prix'] ?>
                        </p>
                        <p class="food-detail">
                            <?php echo $produit['description'] ?>
                        </p>
                        <br>

                        <a href="./update/?=<?= $produit['id']; ?>" class="btn btn-primary">modifier</a>
                        <a href="./delete.php?id=<?= $produit['id']; ?>"">
                            <button class="btn btn-danger"
                                onclick=" return confirm('do you want Delete <?php echo $produit['nom'] ?>');">delete</button></a>

                    </div>
                </div>


            <?php endforeach; ?>
        </div>


    </section>


</body>