    <div class="container">
    <h2 class="text-center mt-1">Categories list</h2>
          <a href="../addcategory/index.php" class="mx-2"><button class="btn btn-outline-success"> Add Categorie </button> </a>
             <div class="row mt-2 py-2">
                 <?php foreach ($categories as $category):
                ?>
                 <div class="col-lg-4">
                        <div class="card">
                             <div class="card-header text-center" style="font-weight:bold;font-size:18px">
                                <?php echo $category['nom'] ?>
                             </div>
                             <div class="card-body text-center">
                                <img width="200px" height="200px"  src="<?php echo $category['photo']?>" alt="Chicke Hawain Pizza" class="img-responsive img-curve rounded shadow">
                             </div>
                             <div class="d-flex justify-content-center mb-2">
                             <a href="./update/?=<?= $category['id']; ?>" class="btn btn-primary mx-2">modifier</a>
                             <a href="delete.php?id=<?= $category['id']; ?>" class="btn btn-danger" onclick=" return confirm('do you want Delete <?php echo $category['nom'] ?>');">suprimer</a>
                             </div>
                        </div>
                        </div>
            <?php endforeach; ?>
             </div>
        </div>
        </div>