<link rel="stylesheet" href="../assets/css/style.css">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    

<body style="background-color: #ececec ;">
    <h2 class="text-center">Categories list</h2>
    <section class="food-menu">
        <div class="container">
        <div class="row mt-4">
         <div class="col">
          <a href="http:./index.php"><button> Add Categorie </button> </a>
          
           </div>
           </div>
            <?php
            foreach ($categories as $category):
                ?>

                <div class="food-menu-box">
                    <div class="food-menu-img">
                        <img src="<?php echo $category['photo']?>" alt="Chicke Hawain Pizza" class="img-responsive img-curve">
                    </div>

                    <div class="food-menu-desc">
                        <h4>
                            <?php echo $category['nom'] ?>
                        </h4>
                        
                      
                        <br>

                        <a href="./update/?=<?= $category['id']; ?>" class="btn btn-primary">modifier</a>
                        <a href="delete.php?id=<?= $category['id']; ?>" class="btn btn-danger" onclick=" return confirm('do you want Delete <?php echo $category['nom'] ?>');">suprimer</a>
                      
                    </div>
                </div>


            <?php endforeach; ?>
        </div>


    </section>


</body>