<style>
     img {
          width: 100%;
          height: 100%;
     }
</style>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
     integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
<div class="container d-flex justify-content-center align-items-center">
     <div class="col-xl-10">
          <div class="row shadow-lg mt-5">
               <div class="col-md-6 py-5 mt-4">
                    <form action="index.php" method="post">
                         <input type="email" name="Email" placeholder="Entrer votre email"
                              class="form-control mb-4 mt-4 <?= array_key_exists('Email', $errors) ? 'is-invalid' : '' ?> "
                              value="<?= $Email ?>" id="exampleInputEmail1">
                         <small class="text-danger">
                              <?php echo array_key_exists("Email", $errors) ? $errors['Email'] : '' ?>
                         </small>

                         <div class="d-flex justify-content-center mb-2">
                              <div class="g-recaptcha " data-sitekey="6Ldl-BUjAAAAAFdE1e3w9KBQLPoPwBJWBWlCT7GE"></div>
                         </div>

                         <div class="text-center mb-4">
                              <button name="suivant" class="btn btn-success" type="submit">Suivant</button>
                              
                         </div>
                    </form>
                    <div class="text-center">
                         <a href="../login/"><button class="btn btn-secondary">cancel</button> </a>
                    </div>
               </div>
               <div class="col-md-6 ">
                    <lottie-player src="https://assets7.lottiefiles.com/packages/lf20_z3pnisgt.json" speed="1"
                         style="width: 100%; height: 100%;" loop autoplay></lottie-player>
               </div>
          </div>
     </div>
</div>
<script type="text/javascript">
     var onloadCallback = function () {
          alert("grecaptcha is ready!");
     };
</script>