<link rel="stylesheet" href="../assets/css/style.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

<div class="all container">
    <div class="card shadow-lg mt-3">
        <h3 style="text-align: center;">add product</h3>


        <?php if (array_key_exists("message", $_GET)): ?>
            <div class="alert alert-<?= $_GET['type'] ?>">
                <?php echo $_GET['message'] ?>
            </div>
        <?php endif; ?>

    </div>

    <form class="formu" action="./index.php" method="POST" enctype="multipart/form-data">
        <div class="mb-3">
            <div>
                <label class="form-label">product name</label>
                <input type="text" name="nom"
                    class="form-control <?= array_key_exists('nom', $errors) ? 'is-invalid' : '' ?>" value="<?= $nom ?>"
                    id="exampleInputNom ">
                <small class="text-danger">
                    <?php echo array_key_exists("nom", $errors) ? $errors['nom'] : '' ?>
                </small>
            </div>
            <div>
                <label class="form-label">product price</label>
                <input type="number" name="prix"
                    class="form-control <?= array_key_exists('prix', $errors) ? 'is-invalid' : '' ?>" value="<?= $prix ?>"
                    id="exampleInputprix ">
                <small class="text-danger">
                    <?php echo array_key_exists("prix", $errors) ? $errors['prix'] : '' ?>
                </small>
            </div>
            <div>
                <label class="form-label">product description</label>
                <input type="text" name="description"
                    class="form-control <?= array_key_exists('description', $errors) ? 'is-invalid' : '' ?>"
                    value="<?= $description ?>" id="exampleInputNom ">
                <small class="text-danger">
                    <?php echo array_key_exists("description", $errors) ? $errors['description'] : '' ?>
                </small>
            </div>
            <div>
                <label class="form-label">product picture</label><br>
                <input type="file" name="photo">
            </div>
            <br>
            <div>
                <label for="form-label">product category</label>
                <br>
                <select name="category" id="">
                    <?php foreach($categories as $category):?>
                    <option value="<?= $category["id"]?>"><?= $category["nom"]?></option>
                    <?php endforeach; ?>

                </select>
            </div>
            <br>



        </div>

        <button type="submit" class="btn btn-primary" name="submit">Submit</button>
    </form>

</div>