<link rel="stylesheet" href="../assets/css/style.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">


<div class="d-flex p-3 m-4 justify-content-center" >
<div class=" card text-center mb-5"  >
<div class="d-flex p-3 m-4 justify-content-center">   
<div class="col-xl-20 col-md-12 col-lg-12">
  <fieldset >
    <legend class="text-center mb-5">Changer mot de passe</legend>
    <form>
  <div class="mb-3">
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Email">
  </div>


  <div class="mb-3">
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Mot de passe">
  </div>

  <div class="mb-3">
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Confirm mot de passe">
  </div>

  <div class="mb-3">
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Code">
  </div>

  <button type="submit" class="btn btn-primary">CHANGER</button>
  <button type="submit" class="btn btn-danger">FERMER</button>
</form>
  </fieldset>
</form>
</div>
</div>
</div>
</div>
